name: Build .NET Framework and Publish to NuGet

on:
  workflow_dispatch:
  push:
    tags: 
      - '^[0-9]+\.[0-9]+\.[0-9]+$'

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    - name: Restore dependencies
      run: nuget restore src/Eliot.UELib.csproj
      
    - name: Build
      run: msbuild src/Eliot.UELib.csproj -t:rebuild -property:Configuration=Remease
      
    - name: Publish Eliot.UELib
      uses: alirezanet/publish-nuget@v3.1.0
      with:
          PROJECT_FILE_PATH: src/Eliot.UELib.csproj
          VERSION_FILE_PATH: src/Eliot.UELib.csproj
          VERSION_REGEX: \>\$\(VersionPrefix\)[0-9]+\.[0-9]+\.[0-9]+\<
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
